In [1]:
import pandapower as pp

net = pp.create_empty_network(sn_mva=100,f_hz=50)

bus0 = pp.create_bus(net,name='GenBus',vn_kv= 22, type='n')
bus1 = pp.create_bus(net,name='Main bus',vn_kv= 22, type='b')
bus2 = pp.create_bus(net,name='Load bus',vn_kv=11 , type='b')
bus3 = pp.create_bus(net,name='Transformer-1 bus',vn_kv= 220, type='b')
bus4 = pp.create_bus(net,name='Transformer-2 bus',vn_kv= 220, type='b')
bus5 = pp.create_bus(net,name='Transformer-3 bus',vn_kv= 110, type='b')
bus6 = pp.create_bus(net,name='Transformer-4 bus',vn_kv= 110, type='b')

pp.create_ext_grid(net , bus0 ,name='Generator',in_service='True')

pp.create_load_from_cosphi(net,bus2,sn_mva=57,cos_phi=0.6,mode='underexcited',const_z_percent =100, scaling=1.1)

pp.create_impedance(net,from_bus=0,to_bus=1,rft_pu=0,xft_pu=0.18,sn_mva=90)

trafo1=pp.create_transformer_from_parameters(net,hv_bus=1 ,lv_bus=3,name='Transformer1',sn_mva=50,vn_hv_kv=22,vn_lv_kv=220,vkr_percent=0,vk_percent=10,pfe_kw=0,i0_percent=0,std_type="50 MVA 22/220 KV")
trafo2=pp.create_transformer_from_parameters(net,hv_bus=4 ,lv_bus=2,name='Transformer2',sn_mva=40,vn_hv_kv=220,vn_lv_kv=11,vkr_percent=0,vk_percent=6,pfe_kw=0,i0_percent=0,std_type="40 MVA 220/11 KV")
trafo3=pp.create_transformer_from_parameters(net,hv_bus=1 ,lv_bus=5,name='Transformer3',sn_mva=40,vn_hv_kv=22,vn_lv_kv=110,vkr_percent=0,vk_percent=6.4,pfe_kw=0,i0_percent=0,std_type="40 MVA 22/110 KV")
trafo4=pp.create_transformer_from_parameters(net,hv_bus=6 ,lv_bus=2,name='Transformer4',sn_mva=40,vn_hv_kv=110,vn_lv_kv=11,vkr_percent=0,vk_percent=8,pfe_kw=0,i0_percent=0,std_type="40 MVA 110/11 KV")

line1=pp.create_line_from_parameters(net,from_bus=3,to_bus=4,length_km=1,r_ohm_per_km=0,x_ohm_per_km=48.8,c_nf_per_km=0, max_i_ka=0.262)
line1=pp.create_line_from_parameters(net,from_bus=5,to_bus=6,length_km=1,r_ohm_per_km=0,x_ohm_per_km=65.43,c_nf_per_km=0,max_i_ka=0.524)

pp.runpp(net,max_iteration=100,numba= False)

C:\Users\Bhavesh Nerpagare\AppData\Roaming\Python\Python310\site-packages\pandapower\auxiliary.py:272: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item, dtype in list(dtypes.iteritems()):
C:\Users\Bhavesh Nerpagare\AppData\Roaming\Python\Python310\site-packages\pandapower\auxiliary.py:272: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item, dtype in list(dtypes.iteritems()):
C:\Users\Bhavesh Nerpagare\AppData\Roaming\Python\Python310\site-packages\pandapower\auxiliary.py:272: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item, dtype in list(dtypes.iteritems()):
C:\Users\Bhavesh Nerpagare\AppData\Roaming\Python\Python310\site-packages\pandapower\auxiliary.py:272: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item, dtype in list(dtypes.iteritems()):
C:\Users\Bhavesh Nerpagare\AppData\Roaming\Python\Python310\site-packages\pandapower\auxiliary.py:272: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item, dtype in list(dtypes.iteritems()):
C:\Users\Bhavesh Nerpagare\AppData\Roaming\Python\Python310\site-packages\pandapower\auxiliary.py:272: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item, dtype in list(dtypes.iteritems()):
C:\Users\Bhavesh Nerpagare\AppData\Roaming\Python\Python310\site-packages\pandapower\auxiliary.py:272: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item, dtype in list(dtypes.iteritems()):
C:\Users\Bhavesh Nerpagare\AppData\Roaming\Python\Python310\site-packages\pandapower\auxiliary.py:272: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item, dtype in list(dtypes.iteritems()):
C:\Users\Bhavesh Nerpagare\AppData\Roaming\Python\Python310\site-packages\pandapower\auxiliary.py:272: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item, dtype in list(dtypes.iteritems()):
C:\Users\Bhavesh Nerpagare\AppData\Roaming\Python\Python310\site-packages\pandapower\auxiliary.py:272: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item, dtype in list(dtypes.iteritems()):
C:\Users\Bhavesh Nerpagare\AppData\Roaming\Python\Python310\site-packages\pandapower\auxiliary.py:272: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item, dtype in list(dtypes.iteritems()):
C:\Users\Bhavesh Nerpagare\AppData\Roaming\Python\Python310\site-packages\pandapower\auxiliary.py:272: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item, dtype in list(dtypes.iteritems()):
C:\Users\Bhavesh Nerpagare\AppData\Roaming\Python\Python310\site-packages\pandapower\auxiliary.py:272: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item, dtype in list(dtypes.iteritems()):
C:\Users\Bhavesh Nerpagare\AppData\Roaming\Python\Python310\site-packages\pandapower\auxiliary.py:272: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item, dtype in list(dtypes.iteritems()):
C:\Users\Bhavesh Nerpagare\AppData\Roaming\Python\Python310\site-packages\pandapower\auxiliary.py:272: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item, dtype in list(dtypes.iteritems()):
C:\Users\Bhavesh Nerpagare\AppData\Roaming\Python\Python310\site-packages\pandapower\auxiliary.py:272: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item, dtype in list(dtypes.iteritems()):

In [2]:
net.res_bus

      vm_pu  va_degree    p_mw     q_mvar
0  1.000000   0.000000 -23.505 -43.632412
1  0.913945  -2.948387   0.000   0.000000
2  0.790443  -8.558328  23.505  31.340001
3  0.858161  -5.237684   0.000   0.000000
4  0.830611  -6.507349   0.000   0.000000
5  0.891440  -3.830610   0.000   0.000000
6  0.817134  -7.167216   0.000   0.000000

In [3]:
net.res_load

     p_mw     q_mvar
0  23.505  31.340001

In [4]:
net.res_ext_grid

     p_mw     q_mvar
0  23.505  43.632412

In [5]:
net.res_line

,p_from_mw,q_from_mvar,p_to_mw,q_to_mvar,pl_mw,ql_mvar,i_from_ka,i_to_ka,i_ka,vm_from_pu,va_from_degree,vm_to_pu,va_to_degree,loading_percent
0,15.66473,23.622679,-15.66473,-22.522720,0.0,1.099959,0.086680,0.086680,0.086680,0.858161,-5.237684,0.830611,-6.507349,33.083871
1,7.84027,12.478045,-7.84027,-11.000266,0.0,1.477779,0.086767,0.086767,0.086767,0.891440,-3.830610,0.817134,-7.167216,16.558631